### ISSUE TITLE
[Feature Request] Button Hold Function

### ISSUE THREAD

**Issue by Its-Just-Luci** [UselessSolutions/BTA_Babric_LegacyUI#17]
idk if this is implementable, but could you add a "hold to craft" feature where if you hold A it will continue crafting so you don't have to mash it, same thing w placing items into containers?

Additionally some way to remap buttons would be 💯

**Comment by UselessBullets** [comment]
Button Holding will be implemented within the next legacy ui update, button remapping I think I want to wait until controller support gets revamped in a future BTA update

**Comment by UselessBullets** [comment]
Showcase of the feature

https://github.com/UselessBullets/BTA_Babric_LegacyUI/assets/80850784/946f0f55-3898-49d8-8bdc-53afd95c7eb2
