### ISSUE TITLE
[Feature Request] Dark Mode?

### ISSUE THREAD

**Issue by Its-Just-Luci** [UselessSolutions/BTA_Babric_LegacyUI#18]
It'd be cool to see a dark-mode option for the legacy UI, not true to how it was on xbox for sure, but I think the world's changed enough for it to be warranted ;)

**Comment by UselessBullets** [comment]
Dark mode can and has been implemented through a texture pack, which is my preferred way of implementing that feature
Check here to download it: https://discord.com/channels/866992171319558144/1136200839187415040
